version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  first-microservice:
    build:
      context: ./crud
    container_name: first_microservice
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/people
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./first-microservice:/app

  second-microservice:
    build:
      context: ./crudFeign
    container_name: second_microservice
    ports:
      - "8081:8081"
    volumes:
      - ./second-microservice:/app
      
volumes:
  postgres_data: